apiVersion: v1
kind: ConfigMap
metadata:
  name: build-script
data:
  build.sh: |
    #!/bin/sh

    set -x

    echo "Extracting uploaded file"
    mkdir /tmp/work
    cd /tmp/work
    export HOME=/tmp/work

    tar xvf /upload/docker.tar

    echo "Running buildah bud"
    buildah bud --storage-driver vfs --isolation chroot --format=oci --tls-verify=true --layers -f Dockerfile -t "index.docker.io/$DOCKER_USER/buildah-test" .

    echo "Pushing to registry"
    # Move creds to a secret and use an env-var here ...
    buildah push --storage-driver vfs --tls-verify=true --creds=$DOCKER_USER:$DOCKER_PASSWORD "index.docker.io/$DOCKER_USER/buildah-test" "docker://index.docker.io/$DOCKER_USER/buildah-test"

    # Wait forever
    tail -f /dev/null
---
apiVersion: v1
kind: Pod
metadata:
  name: buildah-poc
spec:
  initContainers:
  - name: init-upload
    image: alpine
    # Sleep until upload is finished, indicated by
    # a "done" marker file
    command:
    - sh
    - -c
    - while [ ! -e /upload/done ]; do sleep 1; done
    volumeMounts:
    # Shared directory with the main container
    - name: upload
      mountPath: /upload
  containers:
  - name: buildah
    image: quay.io/buildah/stable:v1.11.0
    # Execute script mounted from configmap
    command: [ sh, /opt/build.sh ]
#    securityContext:
#      runAsUser: 2
    envFrom:
    - secretRef:
        name: docker-creds
    volumeMounts:
    # Mount volume with our builder file
    - name: config
      mountPath: /opt
    # Shared directory with init container for the upload
    - name: upload
      mountPath: /upload
    # Required by buildah
    - name: varlibcontainers
      mountPath: /var/lib/containers
    # Seems to be necessary with buildah, needs to be verified
    # if this works on OpenShift (but should)
  volumes:
  - name: config
    configMap:
      name: build-script
  - name: varlibcontainers
    emptyDir: {}
  - name: upload
    emptyDir: {}
